[package]
name = "moneymarket-oracle"
version = "0.0.0"
authors = ["BIG Labs, Terraform Labs PTE, Capapult PTE"]
edition = "2018"
description = "A MoneyMarket custody contract - handles over oracle feed for bAssets"
license = "MIT"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
moneymarket = { path = "../../packages/moneymarket", default-features = false, version = "0.3.1"}
astroport = { path = "../../packages/astroport", default-features = false, version = "2.0.0"}
cosmwasm-std = { workspace = true }
cosmwasm-storage = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cw-storage-plus = { workspace = true }
serde_json = { workspace = true }
cosmwasm-schema = { workspace = true }
rhaki_cw_mock_http_querier = { workspace = true }