[package]
name = "moneymarket-market"
version = "0.0.0"
authors = ["BIG Labs, Terraform Labs PTE, Capapult PTE"]
edition = "2018"
description = "A MoneyMarket custody contract - handles over stable coins"
license = "MIT"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
moneymarket = { path = "../../packages/moneymarket", default-features = false, version = "0.3.1"}
capa-token = { path = "../../packages/capa_token"}
cw20 = { workspace = true }
protobuf = { version = "2", features = ["with-bytes"] }
terraswap = { workspace = true }
cosmwasm-std = { workspace = true }
cosmwasm-storage = { workspace = true }
schemars = { workspace = true }
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = { workspace = true }
cosmwasm-schema = { workspace = true }

