[package]
name = "moneymarket-custody-no-deposit"
version = "0.0.0"
authors = ["BIG Labs, Terraform Labs PTE, Capapult PTE"]
edition = "2018"
description = "A MoneyMarket lunax custody contract - handles over collateral operations"
license = "MIT"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
moneymarket = { workspace = true }
cw20 =  { workspace = true }
astroport = {path = "../../packages/astroport"}
cosmwasm-std = { workspace = true }
cosmwasm-storage = { workspace = true }
schemars = { workspace = true }
serde =  { workspace = true }
thiserror = { workspace = true }
cosmwasm-schema = { workspace = true }
